<!-- SITE TITTLE -->

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-expand-lg navbar-light navigation">
				<a class="navbar-brand" href="index.html">
					<img src="/images/logo.png" alt="">
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto main-nav ">
						<li class="nav-item active">
							<a class="nav-link" href="/">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/home/about">About</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/home/contact">Contact</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/catalog">Catalog</a>
						</li>
						<li class="nav-item dropdown dropdown-slide">
							<a class="nav-link dropdown-toggle" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Categories <span><i class="fa fa-angle-down"></i></span>
							</a>
							<!-- Dropdown list -->
							<div class="dropdown-menu">
								<a class="dropdown-item" href="/catalog/categories">
									<h6>All Categories</h6>
								</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="/catalog/?category=electronics">
									<h6>Electronics</h6>
								</a>
								<a class="dropdown-item" href="/catalog">
									<h6>Restaurants</h6>
								</a>
								<a class="dropdown-item" href="/catalog">
									<h6>Real Estate</h6>
								</a>
								<a class="dropdown-item" href="/catalog">
									<h6>Shoppings</h6>
								</a>
								<a class="dropdown-item" href="/catalog">
									<h6>Jobs</h6>
								</a>
								<a class="dropdown-item" href="/catalog">
									<h6>Vehicles</h6>
								</a>
								<a class="dropdown-item" href="/catalog">
									<h6>Pets</h6>
								</a>
								<a class="dropdown-item" href="/catalog">
									<h6>Services</h6>
								</a>
							</div>
						</li>
					</ul>
					<ul class="navbar-nav ml-auto mt-10">
						<li class="nav-item">
							<a class="nav-link login-button" href="/user/account/login">Login</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-white add-button" href="ad-listing.html"><i class="fa fa-plus-circle"></i> Add Listing</a>
						</li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
</div>