<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Classimax</title>

   <!-- FAVICON -->
   <link href="/images/favicon.png" rel="shortcut icon">
   <!-- lib CSS STYLE -->
   <!-- <link href="lib/jquery-ui/jquery-ui.min.css" rel="stylesheet"> -->
   <!-- Bootstrap -->
   <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css">
   <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap-slider.css">
   <!-- Font Awesome -->
   <link href="/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
   <!-- Owl Carousel -->
   <link href="/lib/slick-carousel/slick/slick.css" rel="stylesheet">
   <link href="/lib/slick-carousel/slick/slick-theme.css" rel="stylesheet">
   <!-- Fancy Box -->
   <link href="/lib/fancybox/jquery.fancybox.pack.css" rel="stylesheet">
   <link href="/lib/jquery-nice-select/css/nice-select.css" rel="stylesheet">
   <!-- CUSTOM CSS -->
   <link href="/css/style.css" rel="stylesheet">


   <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
   <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
   <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body class="body-wrapper">
   <header>
      <?= $this->renderPartial('Shared/header') ?>
   </header>
   <main>
      <?= $this->renderBody() ?>
   </main>
   <?= $this->renderPartial('Shared/footer') ?>
</body>

</html>