<?= $this->layout('Shared/layout') ?>

<section class="section bg-gray">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center mx-auto">
                <div class="404-img">
                    <!-- <img src="/images/404/404.png" class="img-fluid" alt=""> -->
                </div>
                <div class="404-content">
                    <h1 class="display-1 pt-1 pb-2"><?= $model->getCode() ?></h1>
                    <p class="px-3 pb-2 text-dark"><?= $model->getMessage() ?></p>
                    <a href="localhost:8000" class="btn btn-info">GO HOME</a>
                </div>
            </div>
        </div>
    </div>
</section>