<?= $this->layout('Shared/layout') ?>

<!--===============================
=            Hero Area            =
================================-->

<section class="hero-area bg-1 text-center overly">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- Header Contetnt -->
				<div class="content-block">
					<h1>Buy & Sell Near You </h1>
					<p>Join the millions who buy and sell from each other <br> everyday in local communities around the world</p>
					<div class="short-popular-category-list text-center">
						<h2>Popular Category</h2>
						<ul class="list-inline">
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-bed"></i> Hotel</a>
							</li>
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-grav"></i> Fitness</a>
							</li>
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-car"></i> Cars</a>
							</li>
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-cutlery"></i> Restaurants</a>
							</li>
							<li class="list-inline-item">
								<a href="category.html"><i class="fa fa-coffee"></i> Cafe</a>
							</li>
						</ul>
					</div>

				</div>
				<!-- Advance Search -->
				<div class="advance-search">
					<div class="container">
						<div class="row justify-content-center">
							<div class="col-lg-12 col-md-12 align-content-center">
								<form>
									<div class="form-row">
										<div class="form-group col-md-4">
											<input type="text" class="form-control my-2 my-lg-1" id="inputtext4" placeholder="What are you looking for">
										</div>
										<div class="form-group col-md-3">
											<select class="w-100 form-control mt-lg-1 mt-md-2">
												<option>Category</option>
												<option value="1">Top rated</option>
												<option value="2">Lowest Price</option>
												<option value="4">Highest Price</option>
											</select>
										</div>
										<div class="form-group col-md-3">
											<input type="text" class="form-control my-2 my-lg-1" id="inputLocation4" placeholder="Location">
										</div>
										<div class="form-group col-md-2 align-self-center">
											<button type="submit" class="btn btn-primary">Search Now</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
	<!-- Container End -->
</section>

<!--===================================
=            Client Slider            =
====================================-->


<!--===========================================
=            Popular deals section            =
============================================-->

<section class="popular-deals section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h2>Sections</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas, magnam.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<!-- offer 01 -->
			<div class="col-lg-12">
				<div class="category-slider">
					<!-- Client 01 -->
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-bed"></i>
							<h4>Bed</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-bed"></i>
							<h4>Hotels</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-car"></i>
							<h4>Cars</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-cutlery"></i>
							<h4>Restaurants</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-mobile"></i>
							<h4>Automobile</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-film"></i>
							<h4>Gym</h4>
						</a>
					</div>
					<!-- Client 01 -->
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-paragraph"></i>
							<h4>Park</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-play"></i>
							<h4>Play</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-building"></i>
							<h4>Real Estate</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-shopping-bag"></i>
							<h4>Shopping</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-bed"></i>
							<h4>Electronics</h4>
						</a>
					</div>
					<div class="item">
						<a href="#">
							<!-- Slider Image -->
							<i class="fa fa-bed"></i>
							<h4>Health</h4>
						</a>
					</div>

				</div>
			</div>


		</div>
	</div>
</section>
<section class="popular-deals section bg-gray">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h2>Trending Adds</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas, magnam.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<!-- offer 01 -->
			<div class="col-lg-12">
				<div class="trending-ads-slide">
					<div class="col-sm-12 col-lg-4">
						<!-- product card -->
						<div class="product-item bg-light">
							<div class="card">
								<div class="thumb-content">
									<!-- <div class="price">$200</div> -->
									<a href="single.html">
										<img class="card-img-top img-fluid" src="/images/products/products-1.jpg" alt="Card image cap">
									</a>
								</div>
								<div class="card-body">
									<h4 class="card-title"><a href="single.html">11inch Macbook Air</a></h4>
									<ul class="list-inline product-meta">
										<li class="list-inline-item">
											<a href="single.html"><i class="fa fa-folder-open-o"></i>Electronics</a>
										</li>
										<li class="list-inline-item">
											<a href="#"><i class="fa fa-calendar"></i>26th December</a>
										</li>
									</ul>
									<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, aliquam!</p>
									<div class="product-ratings">
										<ul class="list-inline">
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item"><i class="fa fa-star"></i></li>
										</ul>
									</div>
								</div>
							</div>
						</div>



					</div>
					<div class="col-sm-12 col-lg-4">
						<!-- product card -->
						<div class="product-item bg-light">
							<div class="card">
								<div class="thumb-content">
									<!-- <div class="price">$200</div> -->
									<a href="single.html">
										<img class="card-img-top img-fluid" src="/images/products/products-2.jpg" alt="Card image cap">
									</a>
								</div>
								<div class="card-body">
									<h4 class="card-title"><a href="single.html">Full Study Table Combo</a></h4>
									<ul class="list-inline product-meta">
										<li class="list-inline-item">
											<a href="single.html"><i class="fa fa-folder-open-o"></i>Furnitures</a>
										</li>
										<li class="list-inline-item">
											<a href="#"><i class="fa fa-calendar"></i>26th December</a>
										</li>
									</ul>
									<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, aliquam!</p>
									<div class="product-ratings">
										<ul class="list-inline">
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item"><i class="fa fa-star"></i></li>
										</ul>
									</div>
								</div>
							</div>
						</div>



					</div>
					<div class="col-sm-12 col-lg-4">
						<!-- product card -->
						<div class="product-item bg-light">
							<div class="card">
								<div class="thumb-content">
									<!-- <div class="price">$200</div> -->
									<a href="single.html">
										<img class="card-img-top img-fluid" src="/images/products/products-3.jpg" alt="Card image cap">
									</a>
								</div>
								<div class="card-body">
									<h4 class="card-title"><a href="single.html">11inch Macbook Air</a></h4>
									<ul class="list-inline product-meta">
										<li class="list-inline-item">
											<a href="single.html"><i class="fa fa-folder-open-o"></i>Electronics</a>
										</li>
										<li class="list-inline-item">
											<a href="#"><i class="fa fa-calendar"></i>26th December</a>
										</li>
									</ul>
									<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, aliquam!</p>
									<div class="product-ratings">
										<ul class="list-inline">
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item"><i class="fa fa-star"></i></li>
										</ul>
									</div>
								</div>
							</div>
						</div>



					</div>
					<div class="col-sm-12 col-lg-4">
						<!-- product card -->
						<div class="product-item bg-light">
							<div class="card">
								<div class="thumb-content">
									<!-- <div class="price">$200</div> -->
									<a href="single.html">
										<img class="card-img-top img-fluid" src="/images/products/products-2.jpg" alt="Card image cap">
									</a>
								</div>
								<div class="card-body">
									<h4 class="card-title"><a href="single.html">Full Study Table Combo</a></h4>
									<ul class="list-inline product-meta">
										<li class="list-inline-item">
											<a href="single.html"><i class="fa fa-folder-open-o"></i>Furnitures</a>
										</li>
										<li class="list-inline-item">
											<a href="#"><i class="fa fa-calendar"></i>26th December</a>
										</li>
									</ul>
									<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, aliquam!</p>
									<div class="product-ratings">
										<ul class="list-inline">
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item selected"><i class="fa fa-star"></i></li>
											<li class="list-inline-item"><i class="fa fa-star"></i></li>
										</ul>
									</div>
								</div>
							</div>
						</div>



					</div>
				</div>
			</div>


		</div>
	</div>
</section>

<!--====================================
=            Call to Action            =
=====================================-->

<section class="call-to-action overly bg-3 section-sm">
	<!-- Container Start -->
	<div class="container">
		<div class="row justify-content-md-center text-center">
			<div class="col-md-8">
				<div class="content-holder">
					<h2>Start today to get more exposure and
						grow your business</h2>
					<ul class="list-inline mt-30">
						<li class="list-inline-item"><a class="btn btn-main" href="ad-listing.html">Add Listing</a></li>
						<li class="list-inline-item"><a class="btn btn-secondary" href="category.html">Browser Listing</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>

<section class="stores section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h2>More Stores</h2>
				</div>
				<!-- First Letter -->
				<div class="block">
					<!-- Store First Letter -->
					<h5 class="store-letter">#</h5>
					<hr>
					<!-- Store Lists -->
					<div class="row">
						<!-- Store List 01 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 02 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 03 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 04 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- Second Letter -->
				<div class="block">
					<!-- Store First Letter -->
					<h5 class="store-letter">A</h5>
					<hr>
					<!-- Store Lists -->
					<div class="row">
						<!-- Store List 01 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 02 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 03 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 04 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- Third Letter -->
				<div class="block">
					<!-- Store First Letter -->
					<h5 class="store-letter">B</h5>
					<hr>
					<!-- Store Lists -->
					<div class="row">
						<!-- Store List 01 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 02 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 03 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 04 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- Fourth Letter -->
				<div class="block">
					<!-- Store First Letter -->
					<h5 class="store-letter">C</h5>
					<hr>
					<!-- Store Lists -->
					<div class="row">
						<!-- Store List 01 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 02 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 03 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
						<!-- Store List 04 -->
						<div class="col-md-3 col-sm-6">
							<ul class="store-list">
								<li><a href="#">1 - 800 - Got - Junk?</a></li>
								<li><a href="#">1000 bulbs.com</a></li>
								<li><a href="#">180 packrat.com</a></li>
								<li><a href="#">3 day blinds</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>