<?= $this->layout('Shared/layout') ?>

<section class="login py-5 border-top-1">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-8 align-item-center">
                <div class="border">
                    <h3 class="bg-gray p-4">Login Now</h3>
                    <form method="post" action="/user/account/login">
                        <fieldset class="p-4">
                            <input type="text" placeholder="Username" class="border p-3 w-100 my-2" id="InputEmail" name="Username" required>
                            <input type="password" placeholder="Password" class="border p-3 w-100 my-2" id="InputPassword" name="Password" required>
                            <div class="loggedin-forgot">
                                <input type="checkbox" id="InputRemember" name="Remember">
                                <label for="keep-me-logged-in" class="pt-3 pb-2">Keep me logged in</label>
                            </div>
                            <button type="submit" class="d-block py-3 px-5 bg-primary text-white border-0 rounded font-weight-bold mt-3">Log in</button>
                            <a class="mt-3 d-block  text-primary" href="#" id="InputForget" name="ForgetPassword">Forget Password?</a>
                            <a class="mt-3 d-inline-block text-primary" href="/user/account/register">Register Now</a>
                        </fieldset>
                        <?= $this->Html->AntiforgeryToken() ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>